nome_peer: bob
ip: 127.0.0.1
porta: 7002
storage_dir: data/peer-bob
log_path: logs/peer-bob.log
log_level: INFO
trackers:
  - { tracker_id: tracker-1, ip: 127.0.0.1, api_port: 8001 }
  - { tracker_id: tracker-2, ip: 127.0.0.1, api_port: 8002 }
  - { tracker_id: tracker-3, ip: 127.0.0.1, api_port: 8003 }

chunk_size_bytes: 262144
seed_report_interval_seconds: 180
chunk_request_timeout_seconds: 10
download_pool_size: 8
